// Mock pour react-native-reanimated sur le web
import { View, Text, Animated } from 'react-native'

export default {
  View: View,
  Text: Text,
  ScrollView: Animated.ScrollView,
  Image: Animated.Image,
  createAnimatedComponent: (component: any) => component,
  Value: Animated.Value,
  event: () => {},
  add: () => {},
  sub: () => {},
  multiply: () => {},
  divide: () => {},
  modulo: () => {},
  sqrt: () => {},
  sin: () => {},
  cos: () => {},
  exp: () => {},
  round: () => {},
  lessThan: () => {},
  eq: () => {},
  greaterThan: () => {},
  lessOrEq: () => {},
  greaterOrEq: () => {},
  neq: () => {},
  and: () => {},
  or: () => {},
  not: () => {},
  defined: () => {},
  set: () => {},
  concat: () => {},
  cond: () => {},
  block: () => {},
  call: () => {},
  debug: () => {},
  onChange: () => {},
  startClock: () => {},
  stopClock: () => {},
  clockRunning: () => {},
  timing: () => {},
  spring: () => {},
  decay: () => {},
  sequence: () => {},
  parallel: () => {},
  stagger: () => {},
  loop: () => {},
  proc: () => {},
  useSharedValue: () => ({ value: 0 }),
  useAnimatedStyle: () => ({}),
  useAnimatedGestureHandler: () => ({}),
  useAnimatedReaction: () => {},
  useDerivedValue: () => ({ value: 0 }),
  withTiming: (value: any) => value,
  withSpring: (value: any) => value,
  withDecay: (value: any) => value,
  withRepeat: (value: any) => value,
  withSequence: (value: any) => value,
  cancelAnimation: () => {},
  runOnJS: (fn: any) => fn,
  runOnUI: (fn: any) => fn,
  Easing: {
    linear: () => {},
    ease: () => {},
    quad: () => {},
    cubic: () => {},
    poly: () => {},
    sin: () => {},
    circle: () => {},
    exp: () => {},
    elastic: () => {},
    back: () => {},
    bounce: () => {},
    bezier: () => {},
    in: () => {},
    out: () => {},
    inOut: () => {},
  },
}
